import { createHmac, createCipheriv, createDecipheriv, createHash, randomBytes, timingSafeEqual } from "node:crypto";
import https from "node:https";
import { checkServerIdentity as tlsCheckServerIdentity } from "node:tls";
import { and, eq, sql } from "drizzle-orm";
import {
  isPublicUnicastIp,
  resolvePublicTarget,
  type AddressResolver,
} from "./net/public-address";
import { getDb } from "./db/client";
import { isMissingSchemaError } from "./db/pg-errors";
import { webhooks } from "./db/schema";
import { logServerErrorSafe } from "@/lib/util/log-safe";

// ============================================================
// Vouch — webhook notifications (2026-08-05 R&D, C-9).
//
// WHY. Vouch was a pull-only API: a customer who gated x402 settlement on a
// score had no way to learn that the world changed BETWEEN their lookups —
// an agent they had scored got blacklisted, or an outcome landed on a verdict
// they were issued. Polling every wallet they ever scored is exactly the
// N-requests-burning pattern the quota system exists to discourage. Webhooks
// turn the score API into a monitoring service, which is what "trust layer"
// has to mean in practice.
//
// EVENTS (deliberately few, all facts rather than scores):
//   list.changed      — the customer's own manual list changed (audit trail
//                       for team accounts; also fires on import).
//   outcome.recorded  — an outcome (auto-detected or partner-reported)
//                       landed on a verdict THIS customer requested.
// A score itself is never pushed: scores are computed on demand and pushing
// cached ones would invite treating a stale number as fresh.
//
// SECURITY POSTURE:
//   - Deliveries are signed (Stripe-style `t=<unix>,v1=<hmac>` over
//     `${t}.${body}`) so the receiver can authenticate us and reject replays.
//   - Webhook URLs are validated against SSRF at registration AND at delivery
//     time (a DNS record can change between the two).
//   - Delivery must never block or fail the request that triggered it:
//     fire-and-forget with a hard timeout, failures only counted.
//   - Consecutive failures auto-disable the endpoint (dead URLs stop costing
//     us egress and stop masking real delivery rates).
//   - The signing secret is generated by us (never chosen by the caller) and
//     shown once at registration, same contract as API keys.
// ============================================================

// endpoint.delisted (2026-08-14, observatory L0): an endpoint whose payTo the
// subscriber has claim-proved (x402_payee_watchers) vanished from the public
// discovery catalog on a complete fetch. Facts only — payload carries the
// resource, the detection date, and the before/after evidence.
export const WEBHOOK_EVENTS = [
  "list.changed",
  "outcome.recorded",
  "watch.verdict_changed",
  "endpoint.delisted",
] as const;
export type WebhookEvent = (typeof WEBHOOK_EVENTS)[number];

export const MAX_WEBHOOKS_PER_KEY = 5;
export const DISABLE_AFTER_FAILURES = 20;
const DELIVERY_TIMEOUT_MS = 5_000;

// ---- pure helpers (unit-tested without a database) -------------------------

export function isWebhookEvent(v: string): v is WebhookEvent {
  return (WEBHOOK_EVENTS as readonly string[]).includes(v);
}

/**
 * SSRF guard. Registration takes an arbitrary URL from an authenticated
 * customer and our server then POSTs to it — the classic pivot into
 * link-local metadata services and internal hosts. Allow only https to a
 * public-looking hostname. Hostname-literal IPs in private/reserved ranges
 * are rejected outright; names are re-checked at delivery time too.
 */
export function isSafeWebhookUrl(raw: string): boolean {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return false;
  }
  if (url.protocol !== "https:") return false;
  if (url.username || url.password) return false;
  const host = url.hostname.toLowerCase();
  if (host === "localhost" || host.endsWith(".localhost") || host.endsWith(".local")) return false;
  if (host.endsWith(".internal") || host === "metadata.google.internal") return false;
  // IPv6 literal
  if (host.startsWith("[") || host.includes(":")) return false;
  // IPv4 literal in private/reserved space
  const v4 = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(host);
  if (v4) {
    const [a, b] = [Number(v4[1]), Number(v4[2])];
    if (a === 0 || a === 10 || a === 127 || a >= 224) return false;
    if (a === 169 && b === 254) return false;
    if (a === 172 && b >= 16 && b <= 31) return false;
    if (a === 192 && b === 168) return false;
    if (a === 100 && b >= 64 && b <= 127) return false; // CGNAT
  }
  if (!host.includes(".") && !v4) return false; // bare single-label names are internal
  return true;
}

// ---- delivery-time SSRF pin (DNS-rebinding defense) -------------------------
//
// isSafeWebhookUrl is a STRING check: it rejects private literals and internal
// names, but a public hostname is only text — nothing stops it from resolving
// to 169.254.169.254 at delivery time. For a trust-layer product that is a
// fatal SSRF: an attacker registers evil.example.com (passes every string
// gate), then flips its A record to the cloud metadata IP right before we
// POST. The invariant we must hold is: *we never open a delivery connection to
// a non-public address*. We hold it by resolving the hostname ourselves,
// requiring EVERY resolved address to be public unicast, and then connecting
// to that exact verified IP literal (see deliverOne) so the transport cannot
// re-resolve into a private range between our check and the socket — the
// TOCTOU window is closed, not merely narrowed.

// The address predicates and the resolver now live in src/lib/net/
// public-address.ts — the observatory's outbound fetches need the same rules
// and a second copy would be a second thing to keep correct. Re-exported here
// because this module is where they were born and where callers import them.
export { isPublicUnicastIp, type AddressResolver };

/**
 * Resolve `hostname` and return a single verified public IP to pin the
 * delivery socket to, or null if it does not resolve or ANY resolved address
 * is non-public. Returning a concrete IP (not just a boolean) is what lets the
 * caller connect by literal address and close the rebinding window.
 */
export async function resolveDeliveryTarget(
  hostname: string,
  resolve?: AddressResolver,
): Promise<{ ip: string; family: 4 | 6 } | null> {
  return resolvePublicTarget(hostname, resolve);
}

export function generateWebhookSecret(): string {
  return `whsec_${randomBytes(24).toString("base64url")}`;
}

const SECRET_AT_REST_PREFIX = "enc.v1.";

function hashKek(raw: string): Buffer {
  return createHash("sha256").update(raw).digest();
}

function webhookSecretKek(): Buffer | null {
  const raw = process.env.WEBHOOK_SECRET_KEK ?? process.env.API_KEY_PEPPER;
  if (!raw) return null;
  return hashKek(raw);
}

/** Current KEK first, then the previous KEK, then the API-key pepper. Deduped. */
function webhookKekList(): Buffer[] {
  const seen = new Set<string>();
  const out: Buffer[] = [];
  for (const raw of [
    process.env.WEBHOOK_SECRET_KEK,
    process.env.WEBHOOK_SECRET_KEK_PREVIOUS,
    process.env.API_KEY_PEPPER,
  ]) {
    if (!raw) continue;
    const key = hashKek(raw);
    const id = key.toString("hex");
    if (seen.has(id)) continue;
    seen.add(id);
    out.push(key);
  }
  return out;
}

/** AES-256-GCM seal. Legacy plaintext rows (no prefix) pass through on open. */
export function sealWebhookSecret(plain: string): string {
  const kek = webhookSecretKek();
  if (!kek) return plain;
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", kek, iv);
  const ciphertext = Buffer.concat([cipher.update(plain, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return `${SECRET_AT_REST_PREFIX}${iv.toString("base64url")}.${ciphertext.toString("base64url")}.${tag.toString("base64url")}`;
}

function decryptSealedWebhookSecret(stored: string, kek: Buffer): string {
  const parts = stored.slice(SECRET_AT_REST_PREFIX.length).split(".");
  if (parts.length !== 3 || !parts[0] || !parts[1] || !parts[2]) {
    throw new Error("webhook_secret_corrupt");
  }
  const decipher = createDecipheriv("aes-256-gcm", kek, Buffer.from(parts[0], "base64url"));
  decipher.setAuthTag(Buffer.from(parts[2], "base64url"));
  return Buffer.concat([
    decipher.update(Buffer.from(parts[1], "base64url")),
    decipher.final(),
  ]).toString("utf8");
}

export type OpenedWebhookSecret = {
  plain: string;
  /** Set when the row should be rewritten under the current primary KEK. */
  reseal: string | null;
};

export function openWebhookSecret(stored: string): OpenedWebhookSecret {
  if (!stored.startsWith(SECRET_AT_REST_PREFIX)) {
    const resealed = sealWebhookSecret(stored);
    return { plain: stored, reseal: resealed === stored ? null : resealed };
  }
  const keks = webhookKekList();
  if (keks.length === 0) {
    throw new Error("webhook_secret_kek_missing");
  }
  let lastError: unknown;
  for (let i = 0; i < keks.length; i++) {
    try {
      const plain = decryptSealedWebhookSecret(stored, keks[i]!);
      return { plain, reseal: i === 0 ? null : sealWebhookSecret(plain) };
    } catch (error) {
      lastError = error;
    }
  }
  throw lastError instanceof Error ? lastError : new Error("webhook_secret_corrupt");
}

/** `t=<unix seconds>,v1=<hex hmac of "<t>.<body>">` */
export function signWebhookPayload(secret: string, body: string, timestampSec: number): string {
  const v1 = createHmac("sha256", secret).update(`${timestampSec}.${body}`).digest("hex");
  return `t=${timestampSec},v1=${v1}`;
}

/** Receiver-side verification — exported so the docs can point at the exact
 *  algorithm and the SDK can ship it. Tolerance guards replays. */
export function verifyWebhookSignature(
  secret: string,
  body: string,
  header: string,
  nowSec: number,
  toleranceSec = 300,
): boolean {
  const parts = new Map(
    header.split(",").map((p) => {
      const i = p.indexOf("=");
      return [p.slice(0, i), p.slice(i + 1)] as const;
    }),
  );
  const t = Number(parts.get("t"));
  const v1 = parts.get("v1");
  if (!Number.isFinite(t) || !v1) return false;
  if (Math.abs(nowSec - t) > toleranceSec) return false;
  const expected = createHmac("sha256", secret).update(`${t}.${body}`).digest("hex");
  const a = Buffer.from(expected);
  const b = Buffer.from(v1);
  return a.length === b.length && timingSafeEqual(a, b);
}

// ---- persistence -----------------------------------------------------------

export interface WebhookRow {
  id: string;
  apiKeyId: string;
  url: string;
  secret: string;
  events: string[];
  active: boolean;
}

export async function listWebhooks(apiKeyId: string): Promise<Omit<WebhookRow, "secret">[]> {
  const db = getDb();
  if (!db) return [];
  try {
    const rows = await db
      .select({
        id: webhooks.id,
        apiKeyId: webhooks.apiKeyId,
        url: webhooks.url,
        events: webhooks.events,
        active: webhooks.active,
      })
      .from(webhooks)
      .where(eq(webhooks.apiKeyId, apiKeyId));
    return rows.map((r) => ({ ...r, events: (r.events as string[]) ?? [] }));
  } catch (error) {
    if (isMissingSchemaError(error)) return [];
    throw error;
  }
}

export async function createWebhook(params: {
  apiKeyId: string;
  url: string;
  events: WebhookEvent[];
}): Promise<{ id: string; secret: string } | { error: "limit_reached" | "store_unavailable" }> {
  const db = getDb();
  if (!db) return { error: "store_unavailable" };
  try {
    const existing = await db
      .select({ n: sql<number>`count(*)` })
      .from(webhooks)
      .where(eq(webhooks.apiKeyId, params.apiKeyId));
    if (Number(existing[0]?.n ?? 0) >= MAX_WEBHOOKS_PER_KEY) {
      return { error: "limit_reached" };
    }
    const secret = generateWebhookSecret();
    const inserted = await db
      .insert(webhooks)
      .values({
        apiKeyId: params.apiKeyId,
        url: params.url,
        secret: sealWebhookSecret(secret),
        events: params.events,
        active: true,
      })
      .returning();
    return { id: inserted[0]!.id, secret };
  } catch (error) {
    if (isMissingSchemaError(error)) return { error: "store_unavailable" };
    throw error;
  }
}

export async function deleteWebhook(apiKeyId: string, id: string): Promise<boolean> {
  const db = getDb();
  if (!db) return false;
  try {
    const deleted = await db
      .delete(webhooks)
      .where(and(eq(webhooks.id, id), eq(webhooks.apiKeyId, apiKeyId)))
      .returning();
    return deleted.length > 0;
  } catch (error) {
    if (isMissingSchemaError(error)) return false;
    throw error;
  }
}

// ---- delivery --------------------------------------------------------------

/**
 * POST `body` over HTTPS to `url`, but with the TCP connection PINNED to the
 * already-verified `ip`: we set `host` to the literal IP (so the OS never
 * re-resolves the name and cannot be rebound), keep SNI + the Host header +
 * certificate validation bound to the real hostname (so TLS is unchanged), and
 * refuse to follow redirects (a 3xx at delivery is an SSRF vector). Any error,
 * timeout, or non-2xx resolves to `false` — delivery failures are only counted,
 * never thrown, so a webhook can never slow or break the triggering request.
 */
function postPinned(
  url: URL,
  ip: string,
  body: string,
  headers: Record<string, string>,
): Promise<boolean> {
  return new Promise<boolean>((resolve) => {
    let settled = false;
    const finish = (ok: boolean) => {
      if (settled) return;
      settled = true;
      resolve(ok);
    };
    try {
      const req = https.request(
        {
          host: ip, // connect to the verified address, not the name
          servername: url.hostname, // SNI stays the real host
          port: url.port ? Number(url.port) : 443,
          path: `${url.pathname}${url.search}`,
          method: "POST",
          headers: { ...headers, Host: url.hostname },
          // validate the presented cert against the hostname, never the IP
          checkServerIdentity: (_host, cert) => tlsCheckServerIdentity(url.hostname, cert),
          timeout: DELIVERY_TIMEOUT_MS,
        },
        (res) => {
          const status = res.statusCode ?? 0;
          res.resume(); // drain so the socket can close
          finish(status >= 200 && status < 300); // 3xx is NOT followed
        },
      );
      req.on("error", () => finish(false));
      req.on("timeout", () => {
        req.destroy();
        finish(false);
      });
      req.end(body);
    } catch {
      finish(false);
    }
  });
}

async function recordDeliveryFailure(id: string): Promise<void> {
  const db = getDb();
  if (!db) return;
  try {
    await db
      .update(webhooks)
      .set({
        failureCount: sql`${webhooks.failureCount} + 1`,
        active: sql`CASE WHEN ${webhooks.failureCount} + 1 >= ${DISABLE_AFTER_FAILURES} THEN false ELSE ${webhooks.active} END`,
      })
      .where(eq(webhooks.id, id));
  } catch (error) {
    if (!isMissingSchemaError(error)) logServerErrorSafe("webhook_bookkeeping", error);
  }
}

async function deliverOne(row: WebhookRow, eventType: WebhookEvent, payload: unknown): Promise<void> {
  const db = getDb();
  // Re-validate at delivery time: the URL was checked at registration, but
  // this is the moment we actually egress.
  if (!isSafeWebhookUrl(row.url)) {
    return;
  }
  let url: URL;
  try {
    url = new URL(row.url);
  } catch {
    return;
  }
  // DNS-rebinding pin: resolve NOW, require every resolved address to be
  // public, and connect to that verified IP literal below. A hostname whose
  // record flipped to a private/metadata IP is dropped here, before any socket
  // opens. This is the invariant enforcement, not a best-effort narrowing.
  const target = await resolveDeliveryTarget(url.hostname);
  if (!target) {
    return; // unresolvable or resolves to a non-public address → never deliver
  }

  const body = JSON.stringify({
    id: `evt_${randomBytes(12).toString("base64url")}`,
    type: eventType,
    createdAt: new Date().toISOString(),
    data: payload,
  });
  let opened: OpenedWebhookSecret;
  try {
    opened = openWebhookSecret(row.secret);
  } catch (error) {
    logServerErrorSafe("webhook_secret_open", error);
    await recordDeliveryFailure(row.id);
    return;
  }
  if (opened.reseal && db) {
    try {
      await db.update(webhooks).set({ secret: opened.reseal }).where(eq(webhooks.id, row.id));
    } catch (error) {
      if (!isMissingSchemaError(error)) logServerErrorSafe("webhook_secret_reseal", error);
    }
  }
  const signature = signWebhookPayload(opened.plain, body, Math.floor(Date.now() / 1000));

  const ok = await postPinned(url, target.ip, body, {
    "Content-Type": "application/json",
    "Vouch-Signature": signature,
    "User-Agent": "vouch-webhooks/1",
  });

  if (!db) return;
  try {
    if (ok) {
      await db
        .update(webhooks)
        .set({ failureCount: 0, lastDeliveredAt: new Date() })
        .where(eq(webhooks.id, row.id));
    } else {
      await recordDeliveryFailure(row.id);
      return;
    }
  } catch (error) {
    if (!isMissingSchemaError(error)) logServerErrorSafe("webhook_bookkeeping", error);
  }
}

/**
 * Fire an event at every active endpoint the api key has subscribed to it.
 * Fire-and-forget by contract: callers `void` this — a webhook must never
 * slow down or fail the request that triggered it.
 */
export async function dispatchWebhookEvent(
  apiKeyId: string | null,
  eventType: WebhookEvent,
  payload: unknown,
): Promise<void> {
  if (!apiKeyId) return;
  const db = getDb();
  if (!db) return;
  let rows: WebhookRow[];
  try {
    const found = await db
      .select()
      .from(webhooks)
      .where(and(eq(webhooks.apiKeyId, apiKeyId), eq(webhooks.active, true)));
    rows = found.map((r) => ({
      id: r.id,
      apiKeyId: r.apiKeyId,
      url: r.url,
      secret: r.secret,
      events: (r.events as string[]) ?? [],
      active: r.active,
    }));
  } catch (error) {
    if (!isMissingSchemaError(error)) logServerErrorSafe("webhook_lookup", error);
    return;
  }

  await Promise.all(
    rows
      .filter((r) => r.events.includes(eventType))
      .map((r) =>
        deliverOne(r, eventType, payload).catch((error) => logServerErrorSafe("webhook_delivery", error)),
      ),
  );
}
